/**
 * Backend Build Script for FlowDesk
 * Uses esbuild to bundle the TypeScript backend into a single CommonJS file
 * for distribution with Electron.
 */

const esbuild = require('esbuild');
const path = require('path');
const fs = require('fs');

// Ensure dist directory exists
const distDir = path.resolve(__dirname, 'dist');
if (!fs.existsSync(distDir)) {
    fs.mkdirSync(distDir, { recursive: true });
}

console.log('🚀 Building FlowDesk Backend...');

esbuild.build({
    entryPoints: ['server.ts'],
    outfile: 'dist/server.cjs',
    bundle: true,
    platform: 'node',
    target: 'node18',
    format: 'cjs',

    // External modules that should NOT be bundled
    // These either:
    // 1. Have native bindings that can't be bundled (playwright, bcryptjs)
    // 2. Need to be resolved at runtime from node_modules
    external: [
        // Native/binary modules
        'playwright',
        'playwright-core',
        'bcryptjs',
        'fsevents',
        'better-sqlite3',

        // Modules with complex require patterns
        '@browserbasehq/sdk',
        '@browserbasehq/stagehand',

        // Node built-ins (esbuild handles most, but be explicit for edge cases)
        'crypto',
        'fs',
        'path',
        'os',
        'child_process',
        'net',
        'http',
        'https',
        'url',
        'stream',
        'util',
        'events',
        'buffer',
        'querystring',
        'zlib',
        'tls',
        'dns',
        'dgram',
        'cluster',
        'readline',
        'tty',
        'worker_threads',
        'perf_hooks',
        'async_hooks',
        'inspector',
        'assert',
        'v8',
        'vm',
        'constants',
        'module',
    ],

    // Source maps for debugging in production
    sourcemap: true,

    // Don't minify - easier to debug production issues
    minify: false,

    // Keep names for better stack traces
    keepNames: true,

    // Log build information
    logLevel: 'info',

    // Resolve .js imports to .ts files (for TypeScript with .js extensions in imports)
    resolveExtensions: ['.ts', '.js', '.json'],

    // Define environment for conditional code
    define: {
        'process.env.NODE_ENV': '"production"'
    },

    // Banner to add context to the built file
    banner: {
        js: `
/**
 * FlowDesk Backend - Bundled Server
 * Built: ${new Date().toISOString()}
 * 
 * This file is auto-generated by esbuild.
 * Do not edit directly.
 */
`.trim()
    }
}).then(() => {
    console.log('✅ Backend build complete: dist/server.cjs');

    // Verify the output file exists
    const outputPath = path.resolve(__dirname, 'dist', 'server.cjs');
    if (fs.existsSync(outputPath)) {
        const stats = fs.statSync(outputPath);
        const sizeMB = (stats.size / (1024 * 1024)).toFixed(2);
        console.log(`📦 Bundle size: ${sizeMB} MB`);
    }
}).catch((error) => {
    console.error('❌ Build failed:', error);
    process.exit(1);
});
