-- Create the local_storage table
create table public.local_storage (
  id bigint generated by default as identity primary key,
  account_id text not null,
  platform text not null,
  data jsonb default '{}'::jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()),

  -- Create a unique constraint to allow upserts on (account_id, platform)
  constraint local_storage_account_platform_key unique (account_id, platform)
);

-- Enable Row Level Security (RLS)
alter table public.local_storage enable row level security;

-- Create a policy that allows all operations (public access for this automation tool)
-- WARNING: Adjust this policy for production environments
create policy "Enable all access for local_storage" on public.local_storage
  for all using (true) with check (true);
